export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT='REMOVE_INGREDIENT';
export const SET_INGREDIENTS='SET_INGREDIENTS';
export const FETCH_INGREDIENT_FAIL = 'FETCH_INGREDIENT_FAIL';

export const PURCHASE_BURGER_STARTING ='PURCHASE_BURGER_STARTING'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAILS = 'PURCHASE_BURGER_FAILS';
export const PURCHASE_INIT='PURCHASE_INIT';


export const FETCH_ORDERS_START ='FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS ='FETCH_ORDERS_SUCCESS'
export const FETCH_ORDER_FAILS ='FETCH_ORDER_FAILS'


export const AUTH_START = 'AUTH_START'
export const AUTH_SUCCESS= 'AUTH_SUCCESS'
export const AUTH_FAIL = 'AUTH_FAIL'
